ten-dollar-app/ten-dollar/config/routes.rb
Rails.application.routes.draw do
    root 'items#index'

    resources :sellers
    resources :items

    post '/login' => 'sessions#create' 
    delete '/logout' => 'sessions#destroy'

  

end

ten-dollar-app/ten-dollar/app/models/item.rb
class Item
  include Mongoid::Document
  field :price, type: Float
  field :item_tag, type: String
  field :description, type: String
  field :category, type: String
  field :search_tags, type: String
  field :shipping_cost, type: Float
  field :sold, type: Mongoid::Boolean
  validates_numericality_of :price, less_than_or_equal_to: 10.00, message: "Item Price Must be $10 or Less"
  belongs_to :seller
  mount_uploader :image, AvatarUploader
end

ten-dollar-app/ten-dollar/app/models/seller.rb
class Seller
  include Mongoid::Document
  field :username, type: String
  field :password_digest, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :phone, type: String
  field :email, type: String
  has_many :items
  validates_uniqueness_of :username

  
  def password=(unencrypted_password)

	self.password_digest = BCrypt::Password.create(unencrypted_password)

  end

  def authenticate(unencrypted_password)
  		if BCrypt::Password.new(self.password_digest) == unencrypted_password
  			return self
  		else
  			return false
  		end
  end

end

ten-dollar-app/ten-dollar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

ten-dollar-app/ten-dollar/app/controllers/global_controller.rb
class GlobalVarController < ApplicationController
IS_SELLER = false
end

ten-dollar-app/ten-dollar/app/controllers/items_controller.rb
class ItemsController < ApplicationController


	

	def index

	      
		  if logged_in? == false
		  	@items = Item.where(:description => /.*#{params[:q]}.*/i)
		  	render "buyerindex"
		  else
		  	# @items = current_user.items.where(:description => /.*#{params[:q]}.*/i $or :item_tag => /.*#{params[:q]}.*/i)
		  	@items = current_user.items.where({ :$or => [ { :description => /.*#{params[:q]}.*/i }, { :item_tag => /.*#{params[:q]}.*/i } ] })
		  	render "index"
		  end
		
	end

	def show
		# retrieves ONE specific bean in our database
		# the parms refers to rails object with a key and object hash.  one of the hashes is an :id key.
		#       :id comes from the url specifically the part that has the id specified in the routes
		# Bean is our model
		# .find is method available to our Bean model it comes from mongoid gem
		@item = Item.find(params[:id])
	end

	def new
		# this makes a new one
		flash[:alert] = nil
		@item = Item.new
	end

	def create
		#the params object has some methods like .requre and .permit.  The permit says what attributes can be saved
		# :item is from the model
		# @item = item.new(params.require(:item).permit(:name, :roast, :origin, :quantity))
		#@item = Item.new (item_params)
		@item =current_user.items.new(item_params)
		
		if @item.save
		   flash[:alert] = nil
		   redirect_to items_path
		else
			flash[:alert] = "Item price must be $10 or less.  Please enter a new price."
			render "new"
		end
		
		
			# if not successful go back to new page to reenter the data again
			
	end

	def edit
		# action for retrieving a specific been
		# this is the same code you use for the show action
		flash[:notice] = nil
		@item = Item.find(params[:id])
		@seller = Seller.new.username

	end

	def update
		# this retrieves a specific item from database
		@item = Item.find(params[:id])
		if @item.update_attributes(item_params)
		   flash[:notice] = nil
		   redirect_to items_path
		else
			flash[:notice] = "Item price must be $10 or less.  Please enter a new price."
			render "edit"
		end
		
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to items_path
	end


private
# anyting in this private area 
	def item_params
		params.require(:item).permit(:price, :item_tag, :description, :photo, :category, :search_tags, :shipping_cost, :sold, :seller, :username, :image)
	end

end

ten-dollar-app/ten-dollar/app/controllers/sellers_controller.rb
class SellersController < ApplicationController
	def index
		# retrieves ALL the beans in our database
		@sellers =Seller.all
		
	end

	def show
		# retrieves ONE specific seller in our database
		# the parms refers to rails object with a key and object hash.  one of the hashes is an :id key.
		#       :id comes from the url specifically the part that has the id specified in the routes
		# Seller is our model
		# .find is method available to our Seller model it comes from mongoid gem
		@seller = Seller.find(params[:id])
	end

	def new
		# this makes a new one
		flash[:notice] = nil
		@seller = Seller.new
	end

	def create
		#the params object has some methods like .requre and .permit.  The permit says what attributes can be saved
		# :seller is from the model
				@seller = Seller.new (seller_params)
				if @seller.save 
					# if save is ok go back to index.html
					flash[:notice] = nil
					redirect_to sellers_path
				else
					# if not successful go back to new page to reenter the data again
					flash[:notice] = "This User Name is already used by someone else.  Please choose another User Name."
					render "new"
				end
	end

	def edit
		# action for retrieving a specific Seller
		# this is the same code you use for the show action
		flash[:notice] = nil
		@seller = Seller.find(params[:id])

	end

	def update
		# this retrieves a specific seller from database
		@seller = Seller.find(params[:id])

		if @seller.update_attributes(seller_params)
			redirect_to sellers_path
		else
			flash[:notice] = "This User Name is already used by someone else.  Please choose another User Name."
			render "edit"
		end
	end

	def destroy
		@seller = Seller.find(params[:id])
		@items = Item.where(:seller_id => current_user)
		@items.destroy
		session.delete(:user_id)
		@seller.destroy
		redirect_to items_path
	end


private
# anyting in this private area is only visible to this class
	def seller_params
		params.require(:seller).permit(:username, :password, :first_name, :last_name, :phone, :email, :password)
	end

end

ten-dollar-app/ten-dollar/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create 
		seller = Seller.where(username: params[:login][:username]).first
		if seller && seller.authenticate(params[:login][:password])
			session[:user_id] = seller.id.to_s 
			redirect_to seller_path(seller.id) 
		else 
			redirect_to items_path

		end
	end

	def destroy
		session.delete(:user_id) 
		redirect_to items_path
	end
end

ten-dollar-app/ten-dollar/app/helpers/application_helper.rb
module ApplicationHelper
end

ten-dollar-app/ten-dollar/app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
		
				@current_user ||= Seller.find(session[:user_id])
		
		
	end

	def logged_in?
		
		session[:user_id] != nil
	end

end

ten-dollar-app/ten-dollar/app/views/items/_form.html.erb
    <% if @item.image.url != nil %>
        <%= image_tag @item.image.url, size: "100x100" %><br><br>
    <% end %>
<%= form_for @item do |f| %>
      <div>


        <%= f.label :price %>:
        <%= f.text_field :price%><br><br>
        
        <%= f.label :item_tag, "Item" %>:
        <%= f.text_area :item_tag , size: "35x3" %><br><br>

        <%= f.label :description %>:
        <%= f.text_area :description, size: "35x3" %><br><br>

        <%#= f.label :category %>
        <%#= f.text_field :category %>

        <%#= f.label :search_tags %>
        <%#= f.text_field :search_tags %>

        <%= f.label :shipping_cost %>:
        <%= f.text_field :shipping_cost %><br><br>  

        <%= f.label :username %>:
        

        <%= f.file_field :image %>
      </div>
      

      <div>
        <%= link_to "Cancel", items_path, {:style=>'color:red;', :class => "css_class"}%>
        <%= f.submit %>  

      </div>

  
<% end %> 

ten-dollar-app/ten-dollar/app/views/items/buyerindex.html.erb
<div class="bill"></div>
  
<div class="login">
  <%= form_for :login, url: '/login' do |f| %>

    <%= f.label :username %> 
    <%= f.text_field :username %>
    <%= f.label :password %> 
    <%= f.password_field :password %>
    <%= f.submit 'Log In' %>
  <% end %>
</div>
<h3 id="tenstore">The Ten Dollar Store </h3>

<%= form_tag({controller: "items", action: "index"}, method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q, nil, :size=>100) %>
    <%= submit_tag("Search") %>
<% end %>
<h4 id="search-msg">Leave search box empty and press <b>Search</b> to display all items for sale.</h4>

<h3 id="title">Items for Sale:</h3>



<ul>
  <% @items.each do |item| %>
    <li>
      
      <b>Price:</b> <%= number_to_currency(item.price) %>
      <div class="item-width"><b>Item Tag:</b> <%= link_to item.item_tag, item %> </div>
      <div class="item-width"><b>description:</b> <%= item.description %> <br></div>
      
      <b>Shipping Cost:</b> <%= number_to_currency(item.shipping_cost) %><br><br>
      <% if item.image.url != nil %>
          <%= image_tag item.image.url, size: "100x100"%><br><br>
      <% end %>
    </li><br>
  <% end %>
</ul>

ten-dollar-app/ten-dollar/app/views/items/edit.html.erb
<div class="bill"></div>

<h3 id="tenstore">The Ten Dollar Store </h3>

<h2 id="title">Edit <%= @item.item_tag%></h2><br><br>

<% if flash[:notice] %>
    <br><div class = "flash_msg"><%= flash[:notice] %></div>
<% end %>


<%= render "items/form", object: @item %>


<h3><%= link_to "Delete #{@item.item_tag}", item_path(@item), method: :delete, data: {confirm: "Are you sure you want to delete #{@item.item_tag}?"} %></h3>

ten-dollar-app/ten-dollar/app/views/items/index.html.erb
<div class="bill"></div>
 



<h3 id="tenstore">The Ten Dollar Store </h3>



<%= form_tag({controller: "items", action: "index"}, method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q, nil, :size=>100) %>
    <%= submit_tag("Search") %>
<% end %>
<h4 id="search-msg">Leave search box empty and press <b>Search</b> to display all items for sale.</h4>


<% if logged_in? %>
      <h2>Items listed for sale by: <%= current_user.first_name %> <%= current_user.last_name %></h2><br>
<% else %>
  <h2>User Logged Out</h2><br>

<% end %>
<% if logged_in? %>
    <ul>

      <% @items.each do |item| %>
        <li>

          <b>Price:</b> <%= number_to_currency(item.price) %>
          <div class="item-width"><b>Item:</b> <%= link_to item.item_tag, item %><div> 
          <div class="item-width"><b>description:</b> <%= item.description %> <br></div>
          
          
          <b>Shipping Cost:</b> <%= number_to_currency(item.shipping_cost) %><br><br>
          <% if item.image.url != nil %>
              <%= image_tag item.image.url, size: "100x75"%><br><br>
          <% end %>  
        </li>
        <hr size ="8px" noshade>
      <% end %>
    </ul>

  <% end %>

ten-dollar-app/ten-dollar/app/views/items/new.html.erb
<div class="bill"></div>
<h3 id="tenstore">The Ten Dollar Store </h3>
<h3 id="title">New Item</h3><br><br>


<% if flash[:alert] %>
    <br><div class = "flash_msg"><%= flash[:alert] %></div>
<% end %>


<%= render "items/form", object: @item %>

ten-dollar-app/ten-dollar/app/views/items/show.html.erb
<div class="bill"></div>

<h3 id="tenstore">The Ten Dollar Store </h3>
<h2 id="title"><%= @item.item_tag %></h2><br><br>
<%= image_tag @item.image.url %><br>
<p>
	<b>Price:</b> <%= number_to_currency(@item.price) %><br><br>
	<div class="item-width"><b>Item:</b> <%=@item.item_tag %><br><br> </div>
	<div class="item-width"><b>Description:</b> <%=@item.description%> <br><br></div>
	<b>Shipping Cost:</b><%= number_to_currency(@item.shipping_cost) %> </p>
</p>

<%= link_to "Return to Items List", items_path, {:style=>'color:red;', :class => "css_class"} %>

ten-dollar-app/ten-dollar/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TenDollar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render "shared/navigation" %>


<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

ten-dollar-app/ten-dollar/app/views/sellers/_form.html.erb
<%= form_for @seller do |f| %>
  <div>


    <%= f.label :first_name %>:
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>:
    <%= f.text_field :last_name %>

    <%= f.label :phone %>:
    <%= f.text_field :phone %>

    <%= f.label :email %>:
    <%= f.text_field :email %><br><br>

    <%= f.label "User Name"%>:
    <%= f.text_field :username %>

    <%= f.label :password %> 
    <%= f.password_field :password %>

  </div>
  <div>
    <%= f.submit %> <br><br>
    <%= link_to "Cancel", items_path , {:style=>'color:red;', :class => "css_class"} %>
  </div>
<% end %>

ten-dollar-app/ten-dollar/app/views/sellers/edit.html.erb
<div class="bill"></div>

<h3 id="tenstore">The Ten Dollar Store </h3>


<h1 id="title">Edit <%= @seller.username %></h1>

<% if flash[:notice] %>
    <div class = "flash_msg"><%= flash[:notice] %></div>
<% end %>

<%= render "sellers/form", object: @seller %>

<%= link_to "Delete #{@seller.first_name} #{@seller.last_name}", seller_path(@seller), method: :delete, data: {confirm: "Are you sure you want to delete #{@seller.username}?"} %><br><br>

ten-dollar-app/ten-dollar/app/views/sellers/index.html.erb
<div class="bill"></div>

<h3 id="tenstore">The Ten Dollar Store </h3>

<% if logged_in? %>
		<h2 id="title">Seller: <%=  current_user.first_name %>  <%=  current_user.last_name %></h2><br><br>

		<ul>
		  
		    <li>
		      <%= current_user.first_name %>
		      <%= current_user.last_name %>
		      <%= link_to current_user.username, current_user %>

		    </li>
		 
		</ul>

<% end %>

<%= link_to "Return to Items List", items_path, {:style=>'color:black;', :class => "css_class"} %>

ten-dollar-app/ten-dollar/app/views/sellers/new.html.erb
<div class="bill"></div>

<h3 id="tenstore">The Ten Dollar Store </h3>
<h2 id="title">New Seller</h2>

<% if flash[:notice] %>
    <div class = "flash_msg"><%= flash[:notice] %></div>
  <% end %>

<%= render "sellers/form", object: @seller %>

ten-dollar-app/ten-dollar/app/views/sellers/show.html.erb
<div class="bill"></div>

<h3 id="tenstore">The Ten Dollar Store </h3>



<% if @seller.items.length > 1 %>
		<h3><p>These are <b><%= @seller.first_name %> <%= @seller.last_name %>'s</b> Items for Sale:</p></h3>
<% end %>

<% if @seller.items.length == 1 %>
	  	<h3><p>These is <b><%= @seller.first_name %> <%= @seller.last_name %>'s</b> Item for Sale:</p></h3>
<% end %>

<% if @seller.items.length == 0 %>
		<h3><p> <b><%= @seller.first_name %> <%= @seller.last_name %></b> Has No Items for Sale:</p></h3>
<% end %>

<ul>
	<% @seller.items.each do |item| %>
		<li>
		<%= link_to item.item_tag, item %>
		<%= item.description %> (<%= link_to "Edit", edit_item_path(item) %>)
			
		</li>
	<% end %>
</ul>

<nav>
  
  
  <%= link_to "Display All Items", items_path, {:style=>'color:black;', :class => "css_class"} %>
</nav>

ten-dollar-app/ten-dollar/app/views/shared/_navigation.html.erb
<% if logged_in? %>
	<nav>
	  <%= link_to "Edit Account", edit_seller_path(current_user) %>
	  <%= link_to "Display All Items", items_path %>
	  <%= link_to "Seller's Items", current_user %>
	  <%= link_to "New Item", new_item_path %>
	</nav>
<%end %>

<% if logged_in? == false %>
	<nav>
	  <%= link_to "Create Account", new_seller_path %>
	  <%= link_to "All Items", items_path %>
	</nav>
<% end %>

<% if logged_in? %>
    <%= button_to "Log Out", logout_path , method: 'delete'%>
<% end %>